nf_core_version: 3.1.2
repository_type: pipeline
template:
  author: Tanya Sarkin Jain
  description: A variant caller for PacBio long read sequencing - also can be used
    for PureTarget panel analysis, and quantification of repeat expansions
  force: false
  is_nfcore: true
  name: pacvar
  org: nf-core
  outdir: .
  version: 0.1.0
